"""Semantic roles shared by usage-presentation adapters."""

from enum import StrEnum


class UsageTextRole(StrEnum):
    """Closed semantic roles in usage presentation."""

    PLAIN = "plain"
    DIM = "dim"
    ROBOT = "robot"
    TITLE = "title"
    PRODUCT = "product"
    DESCRIPTION = "description"
    PROMISE = "promise"
    CLAUDE = "claude"
    CODEX = "codex"
    CLAUDE_TITLE = "claude_title"
    CODEX_TITLE = "codex_title"
    MASTHEAD_DIVIDER = "masthead_divider"
    HEADER = "header"
    ACCOUNT_LABEL = "account_label"
    PANEL_META = "panel_meta"
    MODEL_CAPTION = "model_caption"
    ACTIVITY_SINCE = "activity_since"
    MODEL_RULE = "model_rule"
    PLAN_MAX = "plan_max"
    PLAN_TEAM = "plan_team"
    PLAN_GREEN = "plan_green"
    PLAN_YELLOW = "plan_yellow"
    PLAN_DIM = "plan_dim"
    CURSOR = "cursor"
    ADVISORY = "advisory"
    RESET = "reset"
    LEGEND = "legend"
    HEAT_ZERO = "heat_zero"
    HEAT_GREEN = "heat_green"
    HEAT_CYAN = "heat_cyan"
    HEAT_YELLOW = "heat_yellow"
    HEAT_RED = "heat_red"
    FOOTER_KEYS = "footer_keys"
    FOOTER_HELP = "footer_help"
    FOOTER_PROGRESS = "footer_progress"
    FOOTER_CONFIRMATION = "footer_confirmation"
    FOOTER_ERROR = "footer_error"
