"""Canonical Codex app-server method names."""

ACCOUNT_LOGIN_COMPLETED_METHOD = "account/login/completed"
ACCOUNT_LOGIN_START_METHOD = "account/login/start"
ACCOUNT_READ_METHOD = "account/read"
ACCOUNT_CHATGPT_AUTH_REFRESH_METHOD = "account/chatgptAuthTokens/refresh"
ACCOUNT_UPDATED_METHOD = "account/updated"
AUTH_STATUS_METHOD = "getAuthStatus"
CONFIG_READ_METHOD = "config/read"
INITIALIZED_METHOD = "initialized"
INITIALIZE_METHOD = "initialize"
MCP_SERVER_STATUS_LIST_METHOD = "mcpServerStatus/list"
MCP_SERVER_STATUS_UPDATED_METHOD = "mcpServerStatus/updated"
MODEL_PROVIDER_CAPABILITIES_READ_METHOD = (
    "modelProvider/capabilities/read"
)
THREAD_REALTIME_CLOSED_METHOD = "thread/realtime/closed"
THREAD_REALTIME_START_METHOD = "thread/realtime/start"
THREAD_REALTIME_STARTED_METHOD = "thread/realtime/started"
TURN_COMPLETED_METHOD = "turn/completed"
TURN_START_METHOD = "turn/start"
TURN_STARTED_METHOD = "turn/started"
