# typed: false
# frozen_string_literal: true

# Sidekick-Usages - Homebrew formula.
#
# Auto-generated by packaging/homebrew/generate.py - do not edit by hand.
# Regenerate after a release with:
#
#   uv run packaging/homebrew/generate.py --output <path>
#
# End-user install:
#
#   brew tap Sawmonabo/tap
#   brew install sidekick-usages
class SidekickUsages < Formula
  include Language::Python::Virtualenv

  desc "Check Claude Code and Codex CLI usage across multiple accounts"
  homepage "https://github.com/Sawmonabo/sidekick-usages"
  url "https://github.com/Sawmonabo/sidekick-usages/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "0eef1f1d347e700a9afb996ef54fa4c0a2d03baa247406c606dd5bd77bb0d214"
  license "Apache-2.0"
  head "https://github.com/Sawmonabo/sidekick-usages.git", branch: "main"

  depends_on "python@3.14"

  # Runtime deps; versions match `uv pip compile pyproject.toml`.
  resource "annotated-doc" do
    url "https://files.pythonhosted.org/packages/57/ba/046ceea27344560984e26a590f90bc7f4a75b06701f653222458922b558c/annotated_doc-0.0.4.tar.gz"
    sha256 "fbcda96e87e9c92ad167c2e53839e57503ecfda18804ea28102353485033faa4"
  end

  resource "click" do
    url "https://files.pythonhosted.org/packages/bb/63/f9e1ea081ce35720d8b92acde70daaedace594dc93b693c869e0d5910718/click-8.3.3.tar.gz"
    sha256 "398329ad4837b2ff7cbe1dd166a4c0f8900c3ca3a218de04466f38f6497f18a2"
  end

  resource "markdown-it-py" do
    url "https://files.pythonhosted.org/packages/06/ff/7841249c247aa650a76b9ee4bbaeae59370dc8bfd2f6c01f3630c35eb134/markdown_it_py-4.2.0.tar.gz"
    sha256 "04a21681d6fbb623de53f6f364d352309d4094dd4194040a10fd51833e418d49"
  end

  resource "mdurl" do
    url "https://files.pythonhosted.org/packages/d6/54/cfe61301667036ec958cb99bd3efefba235e65cdeb9c84d24a8293ba1d90/mdurl-0.1.2.tar.gz"
    sha256 "bb413d29f5eea38f31dd4754dd7377d4465116fb207585f97bf925588687c1ba"
  end

  resource "pygments" do
    url "https://files.pythonhosted.org/packages/c3/b2/bc9c9196916376152d655522fdcebac55e66de6603a76a02bca1b6414f6c/pygments-2.20.0.tar.gz"
    sha256 "6757cd03768053ff99f3039c1a36d6c0aa0b263438fcab17520b30a303a82b5f"
  end

  resource "rich" do
    url "https://files.pythonhosted.org/packages/c0/8f/0722ca900cc807c13a6a0c696dacf35430f72e0ec571c4275d2371fca3e9/rich-15.0.0.tar.gz"
    sha256 "edd07a4824c6b40189fb7ac9bc4c52536e9780fbbfbddf6f1e2502c31b068c36"
  end

  resource "shellingham" do
    url "https://files.pythonhosted.org/packages/58/15/8b3609fd3830ef7b27b655beb4b4e9c62313a4e8da8c676e142cc210d58e/shellingham-1.5.4.tar.gz"
    sha256 "8dbca0739d487e5bd35ab3ca4b36e11c4078f3a234bfce294b0a0291363404de"
  end

  resource "typer" do
    url "https://files.pythonhosted.org/packages/e4/51/9aed62104cea109b820bbd6c14245af756112017d309da813ef107d42e7e/typer-0.25.1.tar.gz"
    sha256 "9616eb8853a09ffeabab1698952f33c6f29ffdbceb4eaeecf571880e8d7664cc"
  end

  def install
    virtualenv_install_with_resources
  end

  test do
    # Verify the binary runs and reports its version.
    assert_match "sidekick-usages #{version}", shell_output("#{bin}/sidekick-usages --version")

    # `list` with no saved accounts must exit 0 and print the empty-state hint.
    output = shell_output("#{bin}/sidekick-usages list 2>&1", 0)
    assert_match(/no accounts saved/i, output)
  end
end
